#!/usr/bin/env python3
"""
Eliva Setup Wizard
Interactive setup to configure Eliva for real-life use
"""

import os
import sys
import json
from pathlib import Path

def print_header():
    print("\n" + "="*60)
    print("🎙️  ELIVA - AI Call Attendant Setup Wizard")
    print("="*60 + "\n")

def print_section(title):
    print(f"\n{'─'*60}")
    print(f"📋 {title}")
    print('─'*60)

def get_input(prompt, default=None, required=True):
    if default:
        full_prompt = f"{prompt} [{default}]: "
    else:
        full_prompt = f"{prompt}: "

    while True:
        value = input(full_prompt).strip()

        if not value and default:
            return default

        if not value and required:
            print("❌ This field is required. Please enter a value.")
            continue

        return value

def validate_api_key(key, service_name):
    if not key or len(key) < 10:
        print(f"⚠️  Warning: {service_name} API key looks invalid (too short)")
        return False
    return True

def create_env_file(config):
    env_path = Path("D:/eliva/.env")

    env_content = f"""# Eliva Configuration
# Generated by Setup Wizard on {os.popen('date /t').read().strip()} {os.popen('time /t').read().strip()}

# ═══════════════════════════════════════════════════════════
# ANTHROPIC API (Required)
# Get your API key from: https://console.anthropic.com/
# ═══════════════════════════════════════════════════════════
ANTHROPIC_API_KEY={config['anthropic_key']}

# ═══════════════════════════════════════════════════════════
# TWILIO CREDENTIALS (Required)
# Get these from: https://console.twilio.com/
# ═══════════════════════════════════════════════════════════
TWILIO_ACCOUNT_SID={config['twilio_sid']}
TWILIO_AUTH_TOKEN={config['twilio_token']}
TWILIO_PHONE_NUMBER={config['twilio_number']}

# ═══════════════════════════════════════════════════════════
# PERSONAL INFORMATION (Required)
# ═══════════════════════════════════════════════════════════
MY_PHONE_NUMBER={config['my_number']}
MY_NAME={config['my_name']}

# ═══════════════════════════════════════════════════════════
# FLASK SETTINGS (Optional)
# ═══════════════════════════════════════════════════════════
FLASK_SECRET_KEY={config.get('secret_key', 'eliva-secret-key-change-me')}
PORT={config.get('port', '5000')}
"""

    with open(env_path, 'w', encoding='utf-8') as f:
        f.write(env_content)

    print(f"\n✅ Created .env file at: {env_path}")

def create_knowledge_base(config):
    kb_dir = Path("D:/eliva/knowledge")
    kb_dir.mkdir(exist_ok=True)

    kb_path = kb_dir / "user_profile.json"

    knowledge = {
        "owner": {
            "name": config['my_name'],
            "title": config.get('title', 'Professional'),
            "current_status": config.get('status', 'busy in a meeting'),
            "available_times": config.get('available', 'after 5 PM on weekdays'),
            "email": config.get('email', 'contact@example.com')
        },
        "urgent_contact_rules": [
            "If it's an emergency, tell the caller to text 'URGENT' to the personal number.",
            "If it's a delivery driver, tell them to leave the package at the front door.",
            "If it's a recruiter/job offer, politely ask them to send an email.",
            "If it's a sales/telemarketer, politely decline and end the call.",
            "If it's friends/family, let them know you'll call them back soon."
        ],
        "faq": [
            {
                "question": "Where are you?",
                "answer": "Currently busy and unavailable to take calls right now."
            },
            {
                "question": "When can I talk to you?",
                "answer": f"Usually free {config.get('available', 'after 5 PM on weekdays')}. You can also send a text message."
            },
            {
                "question": "Can you call me back?",
                "answer": "Yes, I will take your message and contact details, and make sure they get it right away."
            }
        ],
        "custom_instructions": "Be polite, warm, professional, and concise. Keep responses under 2-3 sentences since this is a phone call. Never give out sensitive personal info."
    }

    with open(kb_path, 'w', encoding='utf-8') as f:
        json.dump(knowledge, f, indent=2, ensure_ascii=False)

    print(f"✅ Created knowledge base at: {kb_path}")

def main():
    print_header()

    print("Welcome! This wizard will help you configure Eliva for real-life use.")
    print("You'll need:")
    print("  1. Anthropic API key (https://console.anthropic.com/)")
    print("  2. Twilio account credentials (https://console.twilio.com/)")
    print("  3. A Twilio phone number with Voice capability")
    print("\nPress Enter to continue...")
    input()

    config = {}

    # Section 1: Anthropic API
    print_section("Step 1: Anthropic API Configuration")
    print("Get your API key from: https://console.anthropic.com/settings/keys")
    config['anthropic_key'] = get_input("Enter your Anthropic API key", required=True)
    validate_api_key(config['anthropic_key'], "Anthropic")

    # Section 2: Twilio Credentials
    print_section("Step 2: Twilio Configuration")
    print("Get these from: https://console.twilio.com/")
    config['twilio_sid'] = get_input("Enter your Twilio Account SID", required=True)
    config['twilio_token'] = get_input("Enter your Twilio Auth Token", required=True)
    config['twilio_number'] = get_input("Enter your Twilio phone number (e.g., +1234567890)", required=True)

    # Section 3: Personal Information
    print_section("Step 3: Your Personal Information")
    config['my_name'] = get_input("Your full name", required=True)
    config['my_number'] = get_input("Your personal phone number (e.g., +1987654321)", required=True)
    config['email'] = get_input("Your email address", default="contact@example.com")
    config['title'] = get_input("Your job title/role", default="Professional")
    config['status'] = get_input("Your usual status", default="busy in a meeting")
    config['available'] = get_input("When are you usually available?", default="after 5 PM on weekdays")

    # Section 4: Optional Settings
    print_section("Step 4: Optional Settings")
    print("Press Enter to use default values")
    config['port'] = get_input("Server port", default="5000", required=False)

    import secrets
    config['secret_key'] = secrets.token_hex(32)

    # Summary
    print_section("Configuration Summary")
    print(f"✓ Name: {config['my_name']}")
    print(f"✓ Phone: {config['my_number']}")
    print(f"✓ Email: {config['email']}")
    print(f"✓ Twilio Number: {config['twilio_number']}")
    print(f"✓ Server Port: {config['port']}")

    print("\n" + "="*60)
    confirm = input("\n✅ Ready to create configuration files? (yes/no): ").lower()

    if confirm not in ['yes', 'y']:
        print("❌ Setup cancelled.")
        return

    # Create files
    print("\n📝 Creating configuration files...")
    create_env_file(config)
    create_knowledge_base(config)

    # Final instructions
    print_section("🎉 Setup Complete!")
    print("""
Next steps:

1. 🌐 Deploy Eliva to a public server:
   - Quick test: Use ngrok (see DEPLOYMENT_GUIDE.md)
   - Production: Use Railway.app or your own server

2. 🔗 Configure Twilio Webhooks:
   - Go to: https://console.twilio.com/
   - Navigate to: Phone Numbers → Your Number
   - Set Voice webhook to: https://your-server-url/voice/incoming
   - Set Status callback to: https://your-server-url/voice/status

3. 🚀 Start Eliva:
   - Run: python run.py
   - Access dashboard: http://localhost:5000/

4. 📞 Test it:
   - Call your Twilio number
   - Speak in any language (English, Hindi, Punjabi, etc.)
   - Check the dashboard for call logs

📖 For detailed deployment instructions, see: DEPLOYMENT_GUIDE.md

💡 Tip: Customize your knowledge base at: http://localhost:5000/knowledge-base
    """)

    print("="*60 + "\n")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
